# Generated by Django 2.2.5 on 2020-04-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linnea_demo_app', '0003_post_git_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='FResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('result', models.TextField(default='NO ANSWER!')),
                ('reason', models.TextField(default='NO REASON!')),
                ('git_version', models.TextField(default='LATEST!')),
            ],
            options={
                'verbose_name': 'Failure Result',
                'verbose_name_plural': 'Failure Results',
            },
        ),
        migrations.CreateModel(
            name='SResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('result', models.TextField(default='NO ANSWER!')),
                ('git_version', models.TextField(default='LATEST!')),
            ],
            options={
                'verbose_name': 'Successfull Result',
                'verbose_name_plural': 'Successfull Results',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterField(
            model_name='post',
            name='git_version',
            field=models.TextField(default=''),
        ),
    ]
